version: 2.1
jobs:
  all:
    docker:
      - image: circleci/openjdk:11.0.8-jdk-buster
    working_directory: ~/project
    environment:
      # JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test


workflows:
  version: 2
  default:
    jobs:
      - all

      # Customize the JVM maximum heap limit
      TERM: dumb


