version: 2.1
jobs:
  all:
    docker:
      - image: circleci/openjdk:11.0.8-jdk-buster
    working_directory: ~/project
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2
    steps:
      - checkout

workflows:
  version: 2
  default:
    jobs:
      - all