version: 2.1
jobs:
  all:
    docker:
      - image: circleci/openjdk:11.0.8-jdk-buster
    working_directory: ~/gpact
    environment:
      # JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Install and build the custom version of Web3J
      - run:
         command: |
            cd ..
            git clone https://github.com/drinkcoffee/web3j-rlp
            cd web3j-rlp
            ./gradlew installDist
            cd ../gpact

      # Install Solidity
      - run:
         command: |
            sudo apt-get update
            sudo apt-get -y install software-properties-common
            sudo apt-get update
            sudo add-apt-repository -y ppa:ethereum/ethereum
            sudo apt-get update
            sudo apt-get -y install solc

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test


workflows:
  version: 2
  default:
    jobs:
      - all


