---
version: '3.6'

x-besu-bootnode-def:
  &besu-bootnode-def
  restart: "on-failure"
  image: hyperledger/besu:${BESU_VERSION:-latest}
  env_file:
    - ./.env
  entrypoint:
    - /bin/bash
    - -c
    - |
      /opt/besu/bin/besu public-key export --to=/tmp/bootnode_pubkey;
      /opt/besu/bin/besu \
      --config-file=/config/config.toml \
      --genesis-file=/config/genesis.json \
      --node-private-key-file=/opt/besu/keys/key ;


#      --p2p-host=$$(hostname -i) \

services:
  bc31node1:
    << : *besu-bootnode-def
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=bc31node1,service.version=${BESU_VERSION:-latest}
    volumes:
      - public-keys:/tmp/
      - ./bc31/config.toml:/config/config.toml
      - ./bc31/static-nodes.json:/config/static-nodes.json
      - ./bc31/log-config.xml:/config/log-config.xml
      - ./logs/besu:/tmp/besu
      - ./bc31/genesis.json:/config/genesis.json
      - ./bc31/keys:/opt/besu/keys
    ports:
      - 8310:8545/tcp
    networks:
      gpact-test:
        ipv4_address: 172.16.239.11

  bc32node1:
    << : *besu-bootnode-def
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=bc32node1,service.version=${BESU_VERSION:-latest}
    volumes:
      - public-keys:/tmp/
      - ./bc32/config.toml:/config/config.toml
      - ./bc32/static-nodes.json:/config/static-nodes.json
      - ./bc32/log-config.xml:/config/log-config.xml
      - ./logs/besu:/tmp/besu
      - ./bc32/genesis.json:/config/genesis.json
      - ./bc32/keys:/opt/besu/keys
    ports:
      - 8320:8545/tcp
    networks:
      gpact-test:
        ipv4_address: 172.16.239.12


volumes:
  public-keys:
  prometheus:
  grafana:
  cakeshop:
  member1tessera:
  member2tessera:
  member3tessera:

  splunk:

  ethlogger:

networks:
  gpact-test:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
